import { HttpStatus } from '@nestjs/common';

export enum TimeFilters {
  ANY = 'ANY',
  DAY = 'DAY',
  WEEK = 'WEEK',
  MONTH = 'MONTH',
}

export enum TypeFilters {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  TEMPORARY = 'TEMPORARY',
  CONTRACT = 'CONTRACT',
  INTERNSHIP = 'INTERNSHIP',
  VOLUNTEER = 'VOLUNTEER',
  OTHER = 'OTHER',
}

export enum ExperienceLevelFilters {
  INTERNSHIP = 'INTERNSHIP',
  ENTRY_LEVEL = 'ENTRY_LEVEL',
  ASSOCIATE = 'ASSOCIATE',
  MID_SENIOR = 'MID_SENIOR',
  DIRECTOR = 'DIRECTOR',
  EXECUTIVE = 'EXECUTIVE',
}

export enum WorkingModeFilters {
  ON_SITE = 'ON_SITE',
  REMOTE = 'REMOTE',
  HYBRID = 'HYBRID',
}

export enum IndustryFilters {
  ACCOMMODATION_SERVICES = 'ACCOMMODATION_SERVICES',
  ADMINISTRATIVE_AND_SUPPOR_SERVICES = 'ADMINISTRATIVE_AND_SUPPOR_SERVICES',
  CONSTRUCTION = 'CONSTRUCTION',
  CONSUMER_SERVICES = 'CONSUMER_SERVICES',
  EDUCATION = 'EDUCATION',
  ENTERTAINMENT_PROVIDERS = 'ENTERTAINMENT_PROVIDERS',
  FARMING_RANCHING_FORESTRY = 'FARMING_RANCHING_FORESTRY',
  FINANCIAL_SERVICES = 'FINANCIAL_SERVICES',
  GOVERNMENT_ADMINISTRATION = 'GOVERNMENT_ADMINISTRATION',
  HOSPITALS_AND_HEALTH_CARE = 'HOSPITALS_AND_HEALTH_CARE',
  MANUFACTURING = 'MANUFACTURING',
  PROFESSIONAL_SERVICES = 'PROFESSIONAL_SERVICES',
  REAL_ESTATE_AND_EQUIPMENT_RENTAL_SERVICES = 'REAL_ESTATE_AND_EQUIPMENT_RENTAL_SERVICES',
  RETAIL = 'RETAIL',
  TECHNOLOGY_INFORMATION_AND_MEDIA = 'TECHNOLOGY_INFORMATION_AND_MEDIA',
}
