version: '3'
services:
  nestjs-api:
    build:
      context: .
      target: install-dependencies
    command: npm run start:inspect
    volumes:
      - ./src:/user/src/app/src
    env_file:
      - .env
    ports:
      - '3000:3000'
      - '9229:9229'
